INSERT INTO tblGenre (Genre_Name, Description) 
VALUES
('Pop', 'A genre characterized by catchy melodies and widespread appeal.'),
('Hip-Hop', 'A genre known for rhythmic vocal delivery and strong beats.'),
('Rock', 'A genre featuring electric guitars and a strong rhythm section.'),
('Jazz', 'A genre emphasizing improvisation and complex harmonies.'),
('Classical', 'A genre known for orchestral music and long compositions.'),
('Electronic', 'A genre that involves the use of electronic devices and instruments for music production.'),
('Reggae', 'A genre originating in Jamaica, characterized by offbeat rhythms and socially conscious lyrics.'),
('Blues', 'A genre rooted in African-American traditions, featuring expressive vocals and a 12-bar structure.'),
('Country', 'A genre blending folk, western, and blues elements, often featuring steel guitars and storytelling lyrics.'),
('R&B', 'A genre combining jazz, blues, and gospel, with a focus on soulful vocals and rhythm.'),
('Funk', 'A genre emphasizing groovy bass lines, syncopated rhythms, and danceable beats.'),
('Metal', 'A genre known for its heavy, distorted guitar riffs and powerful vocals.'),
('Soul', 'A genre focusing on strong, emotional vocal delivery and rhythmic beats.'),
('Punk', 'A genre characterized by fast tempos, simple structures, and rebellious themes.'),
('Disco', 'A genre that blends funk and soul, known for its danceable beats and upbeat tempos.'),
('House', 'A genre of electronic dance music characterized by repetitive beats and synthesized melodies.'),
('Techno', 'A genre of electronic music featuring fast beats, synthesized sounds, and repetitive structures.'),
('Trance', 'A genre of electronic dance music known for its uplifting melodies and extended build-ups.'),
('Indie', 'A genre often associated with independent artists, featuring non-mainstream styles and experimental sounds.'),
('Alternative', 'A genre that blends various styles, often with a focus on unconventional sounds and themes.'),
('Acapella', 'A genre where music is performed without instrumental accompaniment, relying on vocals.'),
('Folk', 'A genre characterized by storytelling lyrics and acoustic instrumentation, often passed down through generations.'),
('Gospel', 'A genre rooted in Christian religious traditions, focusing on choir-based vocal performances.'),
('Bluegrass', 'A genre blending traditional Appalachian folk with jazz and blues elements.'),
('K-pop', 'A genre of popular music originating from South Korea, combining elements of pop, hip-hop, and R&B.'),
('Latin', 'A genre encompassing various styles of music from Latin America, often with strong rhythmic elements.'),
('World', 'A genre encompassing diverse music styles from various cultures around the world.'),
('Dancehall', 'A genre of Jamaican popular music, characterized by a strong rhythm and rhythmic vocals.'),
('Ska', 'A genre originating in Jamaica, blending jazz, R&B, and Caribbean rhythms with a fast tempo.'),
('Trap', 'A subgenre of hip-hop, known for its aggressive beats and often dark themes.'),
('Dubstep', 'A genre of electronic music featuring heavy bass, syncopated rhythms, and atmospheric soundscapes.'),
('Grunge', 'A genre that blends punk rock and heavy metal, often featuring distorted guitars and angst-driven lyrics.'),
('Experimental', 'A genre focused on unconventional structures and sounds, often pushing the boundaries of music.'),
('Chillwave', 'A genre of electronic music characterized by nostalgic, lo-fi aesthetics and relaxed tempos.'),
('Synthwave', 'A genre inspired by 1980s electronic music, featuring synthesizers and retro-futuristic sounds.'),
('K-hip hop', 'A genre of hip-hop music originating in South Korea, blending Western hip-hop with local influences.'),
('Afrobeat', 'A genre that blends traditional African rhythms with jazz, funk, and highlife music.'),
('Dance-Pop', 'A genre that combines pop music with elements of electronic dance music, typically designed for dancing.'),
('Baroque', 'A classical music genre from the 17th century, characterized by ornate and elaborate compositions.'),
('Psychedelic', 'A genre known for experimental sounds and effects, often inspired by mind-altering substances.'),
('Lo-fi', 'A genre known for its raw, unpolished sound, often used in background music and study playlists.'),
('Reggaeton', 'A genre of music blending Latin rhythms with hip-hop and dancehall influences.'),
('Hard Rock', 'A subgenre of rock that features aggressive guitar riffs, loud vocals, and powerful drum beats.'),
('Post-Punk', 'A genre that emerged after punk, incorporating more experimental sounds and atmospheres.'),
('Jazz Fusion', 'A genre that blends jazz with other genres like rock, funk, and R&B, often with complex rhythms.'),
('Progressive Rock', 'A genre of rock known for its complex structures, long compositions, and experimental sounds.'),
('New Wave', 'A genre that emerged in the late 1970s, blending punk with electronic and pop influences.'),
('Ambient', 'A genre of electronic music focused on creating atmospheric, minimalistic soundscapes.'),
('Noise', 'A genre characterized by harsh, dissonant sounds and experimental structures.'),
('Glam Rock', 'A genre of rock known for its theatrical performances and eccentric fashion.'),
('Folk Rock', 'A genre combining elements of folk music and rock, often with acoustic guitars and poetic lyrics.'),
('Salsa', 'A genre of Latin music, characterized by its energetic rhythm and danceable melodies.'),
('Cumbia', 'A traditional Colombian genre of music and dance, with a distinctive rhythm and instrumentation.'),
('Bossa Nova', 'A Brazilian genre blending samba and jazz, known for its smooth rhythms and soothing melodies.'),
('Tango', 'A genre originating from Argentina, known for its passionate rhythms and dramatic melodies.'),
('Ska Punk', 'A fusion of ska and punk rock, featuring upbeat rhythms and fast tempos.'),
('Indie Pop', 'A genre blending indie rock and pop, often with catchy melodies and a DIY ethos.'),
('Electropop', 'A genre of pop music that blends electronic elements with traditional pop structures.'),
('Experimental Rock', 'A genre that blends rock with experimental and avant-garde elements.'),
('Nu Metal', 'A genre combining metal with elements of hip-hop, grunge, and alternative rock.'),
('Pop Punk', 'A genre blending punk rock with catchy, pop-inspired melodies and lyrics.'),
('Post-Rock', 'A genre that focuses on atmosphere, texture, and structure, often without a traditional verse-chorus form.'),
('Tech House', 'A subgenre of house music that incorporates elements of techno, often with minimalistic rhythms.'),
('Dub', 'A genre that evolved from reggae, featuring instrumental remixes with heavy use of bass and effects.'),
('Hardcore', 'A genre of punk rock that is faster, more aggressive, and often political in nature.'),
('Grime', 'A genre of UK rap known for its dark, aggressive sound and fast-paced beats.'),
('Pop-Rock', 'A genre blending pop melodies with rock instrumentation, often with mainstream appeal.'),
('Death Metal', 'A subgenre of metal that features distorted guitars, blast beats, and guttural vocals.'),
('Black Metal', 'A subgenre of metal that features atmospheric, dark themes and shrieking vocals.'),
('Screamo', 'A subgenre of hardcore punk and emo that features high-pitched, emotional vocals and aggressive guitars.'),
('Power Metal', 'A subgenre of metal known for its fast tempos, anthemic choruses, and fantasy-inspired themes.'),
('Thrash Metal', 'A subgenre of metal that features fast, aggressive guitar riffs and harsh vocals.'),
('Symphonic Metal', 'A genre that combines metal with orchestral elements, featuring dramatic arrangements and operatic vocals.'),
('Industrial Metal', 'A genre blending metal with industrial music, featuring harsh electronic elements and mechanical sounds.'),
('Post-Hardcore', 'A genre that evolved from hardcore punk, with more complex structures and emotional lyrics.'),
('Shoegaze', 'A genre of alternative rock characterized by dense layers of sound and introspective lyrics.'),
('J-Pop', 'A genre of pop music originating in Japan, blending traditional and modern elements.'),
('Trap Metal', 'A subgenre of metal that blends heavy guitar riffs with trap beats and hip-hop influences.'),
('Tropical House', 'A subgenre of house music with tropical influences, often featuring steel drums and laid-back beats.');
