INSERT INTO tblArtist (RecordLabel_ID, Artist_Name) 
VALUES 
(1, 'Adele'),
(2, 'Drake'),
(3, 'Taylor Swift'),
(4, 'The Beatles'),
(1, 'Beyoncé'),
(2, 'Eminem'),
(3, 'Ed Sheeran'),
(4, 'Pink Floyd'),
(1, 'Shakira'),
(2, 'Kanye West'),
(3, 'Billie Eilish'),
(4, 'Led Zeppelin'),
(1, 'Harry Styles'),
(2, 'Lil Wayne'),
(3, 'Justin Bieber'),
(4, 'Queen'),
(1, 'Rihanna'),
(2, 'Kendrick Lamar'),
(3, 'Ariana Grande'),
(4, 'The Rolling Stones'),
(1, 'Sam Smith'),
(2, 'Travis Scott'),
(3, 'Katy Perry'),
(4, 'Fleetwood Mac'),
(1, 'Sia'),
(2, 'Post Malone'),
(3, 'Shawn Mendes'),
(4, 'The Who'),
(1, 'Justin Timberlake'),
(2, 'Future'),
(3, 'Lorde'),
(4, 'David Bowie'),
(1, 'Lady Gaga'),
(2, 'Jay-Z'),
(3, 'Bruno Mars'),
(4, 'U2'),
(100, 'Drake'),
(2, 'Migos'),
(3, 'Olivia Rodrigo'),
(4, 'The Doors'),
(1, 'Kesha'),
(2, 'Lil Nas X'),
(3, 'Halsey'),
(4, 'The Beach Boys'),
(1, 'John Legend'),
(2, 'Chance the Rapper'),
(3, 'Camila Cabello'),
(4, 'The Clash'),
(1, 'Rita Ora'),
(2, 'Macklemore'),
(3, 'Lizzo'),
(4, 'Green Day'),
(1, 'The Weeknd'),
(2, 'Drake'),
(3, 'Miley Cyrus'),
(4, 'AC/DC'),
(1, 'Nicki Minaj'),
(2, 'Cardi B'),
(3, 'Dua Lipa'),
(4, 'Radiohead'),
(1, 'Miley Cyrus'),
(2, 'Tyler, the Creator'),
(3, 'Post Malone'),
(4, 'The Cure'),
(1, 'Brendon Urie'),
(2, 'Kendrick Lamar'),
(3, 'Maroon 5'),
(4, 'Coldplay'),
(1, 'Niall Horan'),
(2, 'Lil Baby'),
(3, 'Ed Sheeran'),
(4, 'The Smiths'),
(1, 'Ariana Grande'),
(2, 'Drake'),
(3, 'Megan Thee Stallion'),
(4, 'Pearl Jam'),
(1, 'Katy Perry'),
(2, 'J. Cole'),
(3, 'Lady Gaga'),
(4, 'Nirvana'),
(1, 'Demi Lovato'),
(2, 'Post Malone'),
(3, 'Harry Styles'),
(4, 'The Strokes'),
(1, 'Dua Lipa'),
(2, 'Lil Uzi Vert'),
(3, 'Taylor Swift'),
(4, 'The Killers'),
(1, 'Billie Eilish'),
(2, 'Future'),
(3, 'Selena Gomez'),
(4, 'The Police'),
(1, 'John Mayer'),
(2, 'Logic'),
(3, 'Sia'),
(4, 'The Cranberries'),
(1, 'Sia'),
(2, 'Migos'),
(3, 'Adele'),
(4, 'The Velvet Underground'),
(1, 'Shawn Mendes'),
(2, 'Kanye West'),
(3, 'Bruno Mars'),
(4, 'The Kinks'),
(1, 'Ariana Grande'),
(2, 'Drake'),
(3, 'Lana Del Rey'),
(4, 'Arcade Fire'),
(1, 'Ed Sheeran'),
(2, 'Kendrick Lamar'),
(3, 'Katy Perry'),
(4, 'The Pixies');
