INSERT INTO tblRecordLabel (RecordLabel_Name) 
VALUES 
('Sony Music'),
('Universal Music'),
('Warner Music'),
('Atlantic Records'),
('Capitol Records'),
('Columbia Records'),
('Island Records'),
('RCA Records'),
('Def Jam Recordings'),
('EMI Records'),
('Epic Records'),
('Interscope Records'),
('Arista Records'),
('Republic Records'),
('Motown Records'),
('Warner Bros. Records'),
('Maverick Records'),
('Parlophone Records'),
('Virgin Records'),
('A&M Records'),
('Epic Records'),
('Big Machine Records'),
('BMG Rights Management'),
('Polygram'),
('Warner Music UK'),
('Universal Music UK'),
('Sony Music Entertainment'),
('Sony Classical'),
('Geffen Records'),
('Lava Records'),
('Atlantic Records UK'),
('Pias Recordings'),
('Sub Pop Records'),
('Nonesuch Records'),
('XL Recordings'),
('Rough Trade Records'),
('Merge Records'),
('Polyvinyl Records'),
('Creation Records'),
('Sire Records'),
('Matador Records'),
('Kemosabe Records'),
('Republic Records UK'),
('Capitol Music Group'),
('Interscope Geffen A&M Records'),
('Vanguard Records'),
('Elektra Records'),
('Walt Disney Records'),
('Verve Records'),
('Universal Republic Records'),
('Columbia Nashville'),
('Sugar Hill Records'),
('Concord Music Group'),
('Blue Note Records'),
('Alligator Records'),
('Cooking Vinyl'),
('Fearless Records'),
('Dualtone Records'),
('Roadrunner Records'),
('Roadhouse Records'),
('Loud Records'),
('Hollywood Records'),
('Island Def Jam Music Group'),
('Parlophone Music'),
('Warner Music Nashville'),
('Sundazed Music'),
('Atlantic Nashville'),
('Curb Records'),
('Motown Gospel'),
('Cherry Red Records'),
('Cooking Vinyl USA'),
('Reprise Records'),
('Fader Label'),
('Warner Music Australasia'),
('EMI Music Australia'),
('Sony Music Australia'),
('Universal Music Australia'),
('Live Nation Entertainment'),
('Roc Nation'),
('Machete Music'),
('Tuff Gong Records'),
('Glassnote Records'),
('Interscope Records UK'),
('Noisetrade Records'),
('Motor Music'),
('Fat Possum Records'),
('Spinefarm Records'),
('World Circuit Records'),
('Rising Tide Music'),
('ArtistFirst Records'),
('Rounder Records'),
('All Points Music'),
('Shady Records'),
('Young Money Entertainment'),
('Capitol Records Nashville'),
('Epic Records UK'),
('10K Projects'),
('Maverick Music Group'),
('Loma Vista Recordings'),
('Punkcore Records'),
('Apex Records'),
('Oglio Records'),
('Beggars Banquet Records'),
('V2 Records'),
('Loud & Proud Records');

