DROP TABLE IF EXISTS tblRecordLabel;
DROP TABLE IF EXISTS tblArtist;
DROP TABLE IF EXISTS tblVinyl;
DROP TABLE IF EXISTS tblGenre;
DROP TABLE IF EXISTS tblReviews;
DROP TABLE IF EXISTS tblReviewComments;